### ISSUE TITLE
Problem while getting service provider url from RTC 7.0.2 tool with authorization server

### ISSUE THREAD

**Issue by pushpita-sengupta** [OSLC/oslc4net#23]
Downloaded this OSLC4Net build and was trying to retrieve data from RTC 7.0.2. The code is getting authenticated at client.FormLogin() and returning a OK status code. But when it is trying to fetch service provider URL based on catalog URL for the respective project area by the "client.LookupServiceProviderUrl(catalogUrl, projectArea);" it is giving the following response --

{"OSLCC004: The requested resource could not be found. "}
{StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Strict-Transport-Security: max-age=31536000
  WWW-Authenticate: Basic realm="JSA"
  WWW-Authenticate: Bearer realm="JSA"
  X-Powered-By: Servlet/3.0
  X-JSA-AUTHORIZATION-URL: https://jazz702-jas.in.kovair.com:9643/oidc/endpoint/jazzop
  X-JSA-AUTHORIZATION-REDIRECT: https://jazz702-jas.in.kovair.com:9643/oidc/endpoint/jazzop/authorize?client_id=a45241f7523e47938c26a0fb573f3aee&response_type=code&state=security_token1%3DpwXwH5CYJWwSdWMIqE2KVQoJTNvJec6JrJWDg5zURKw%3D%26security_token2%3DC%2BumLl1CViIUQxm2HLp3CxwO0VZuDLR3n8zIi5kE32w%3D%26return%3Dhttps%253A%252F%252Fjazz702-jas.in.kovair.com%253A9443%252Fccm%252Foslc%252Fworkitems%252Fcatalog%26scope%3Dopenid%2Bgeneral%2Bprofile%2Bemail%2B%26impersonation%3Dtrue&scope=openid+general+profile+email+&redirect_uri=https%3A%2F%2Fjazz702-jas.in.kovair.com%3A9443%2Fccm%2Fjsa
  Set-Cookie: JSA_CSRF_b179c159-8dc3-4ecf-910b-0fe1c5969e5c=153579c3-8bea-44af-9d68-947497117191; Path=/ccm; Secure
  Date: Tue, 15 Mar 2022 16:28:58 GMT
  Cache-Control: no-cache="set-cookie, set-cookie2"
  Content-Length: 0
  Content-Language: en-US
  Expires: Thu, 01 Dec 1994 16:00:00 GMT
}}

Do we need to provide any other header or any other mechanism in order to fetch data from RTC 7.0.2(authorization server) via OSLC4Net? Please provide the required fix for the above problem

**Comment by pushpita-sengupta** [comment]
I am having error while using this OSLC4Net project for getting data from RTC 7.0.2 having authorization server.
hey @berezovskyi , @brianking , @jamsden , @fijshion can u help me on this?

**Comment by berezovskyi** [comment]
Hi @pushpita-sengupta, we are considering to put some effort into reviving the project and looking for users interested in a .NET OSLC SDK. Could you please contact me via email if you (and/or your company) has a need for a .NET OSLC SDK? My email is visible in my profile.

**Comment by jadelkhoury** [comment]
Hi @pushpita-sengupta, 

I mentioned you and this post on https://github.com/OSLC/oslc4net/issues/25#issuecomment-1113024551 

I was hoping that more can join efforts to lift and update this library ?

regards
Jad

**Comment by berezovskyi** [comment]
Hi again @pushpita-sengupta,

I just made an [update to the OAuth libs](https://github.com/OSLC/oslc4net/commit/fb29da8f3522ce87ad112ebce49b76bd38b6dd1a). If you still have the code Jazz interaction and can share a small part of it which relates to reading the Root Services, doing the auth, and fetching a Service Provider Catalog, I would be quite thankful. We already have [smoke testing](https://github.com/OSLC/lyo-samples/actions/workflows/maven-smoke.yml) of the Java-based code samples against two live Jazz servers (one with the Basic auth and another with the forms-based auth) and would try to do the same for OSLC4Net.

Thanks in advance,
Andrew

**Comment by berezovskyi** [comment]
Jazz-specific code (OAuth1.0a and Jazz forms auth) was moved into the deprecated solution https://github.com/OSLC/oslc4net/tree/main/OSLC4Net_NETFramework that only supports .NET Framework 4. For now, we do not have any plans to migrate that to .NET 5+/netstandard, but we are ready to consider merging a pull request if you are interested. Closing for now.
