### ISSUE TITLE
Questions about "OslcDialog" in Service Provider

### ISSUE THREAD

**Issue by lll4770** [OSLC/oslc4net#82]
Hi,
I'm a new beginner of OSLC, and I'm learning on your project.
I studied the StockQuoteSample project, I noticed we could add the "OslcDialog" and "OslcQueryCapability" on the same function(GetStockQuotes). From my understanding, this function "GetStockQuotes" is a "GET" function, why can you put the annotation "OslcDialog" on this function? In other words, what functions can we declare as "OslcDialog", and how about the "url" of "OslcDialog"?

**Comment by Jad-elkhouy** [comment]
Hi 

May I suggest you ask these questions on the OSLC forum https://forum.open-services.net/ ? 
This is a general OSLC enquire and I am sure the broarder OSLC community can better help you there.
Jad

**Comment by lll4770** [comment]
Got it, thanks @Jad-elkhouy

**Comment by lll4770** [comment]
I'm going to sign up on the OSLC forum... 
And what I want to know is this https://github.com/OSLC/oslc4net/blob/master/OSLC4Net_SDK/OSLC4Net.StockQuoteSample/Controllers/StockQuoteController.cs#L53; I noticed that the "OslcDialog" and "OslcQueryCapability" are declared on the same function (GetStockQuotes), I also want to know how OslcDialog works

**Comment by jamsden** [comment]
Class StockQuoteController provides the OSLC server for stock quotes. That server provides OSLC delegated dialog, creation factory and query capabilities on stock quotes. Function getStockQuote is a method that returns an RDF representation of a stock quote, it is not directly related to delegated dialogs, creation factories or query capabilities. Rather it is just part of the POST, GET, PUT, DELETE HTTP methods on stock quotes that a typical OSLC server would provide. 

I suggest closing this issue and moving the discussion to the OSLC forum.

**Comment by berezovskyi** [comment]
@lll4770 welcome to OSLC4Net! You are welcome to post questions here or on the forum. But please use https://github.com/OSLC/oslc4net/discussions in the future for the questions, if you prefer to stay on Github. But we can finish discussing this question here, such as not to fragment the conversation.

Regarding your questions:

> [...] function "GetStockQuotes" is a "GET" function, why can you put the annotation "OslcDialog" on this function?

According to the OSLC Core spec, both OSLC Query Capability and the OSLC Selection Dialog endpoints should be requested via an HTTP GET request. There are now discussions in the OSLC Open Project to change this (which I don't support much, as I believe that all idempotent requests should be made using idempotent HTTP verbs, but that's another topic).

> I noticed we could add the "OslcDialog" and "OslcQueryCapability" on the same function(GetStockQuotes). [...] why can you put the annotation "OslcDialog" on this function? In other words, what functions can we declare as "OslcDialog", and how about the "url" of "OslcDialog"?
 
I specifically checked the code behavior and can say that for the time being, these attributes (annotations are called [attributes](https://learn.microsoft.com/en-us/dotnet/csharp/advanced-topics/reflection-and-attributes/) in C#) are only used to build Service and Service Provider definitions (e.g., when you request `curl --location 'http://localhost:7077/api/serviceprovider' \
--header 'Accept: application/rdf+xml'
`).

**Comment by berezovskyi** [comment]
> I also want to know how OslcDialog works

For that, I would like to recommend using the Java reference implementation to see how the dialogs work: https://github.com/oslc-op/refimpl/

Technically, they use HTML iframes and the [postMessage Javascript protocol](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to exchange the data between the client page and the page (e.g., a selection dialog) embedded in an iframe.
